# Generated by Django 4.0.7 on 2022-09-01 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.agency'),
        ),
        migrations.AddField(
            model_name='security',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.agency'),
        ),
        migrations.AddField(
            model_name='resident',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.residence'),
        ),
    ]
