# Generated by Django 4.0.7 on 2022-09-01 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.license')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.agencyadmin')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('is_residential', models.BooleanField(default=False, verbose_name='residential')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.agency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.condoadmin')),
            ],
            options={
                'verbose_name': 'Condo',
                'verbose_name_plural': 'Condos',
                'db_table': 'condo',
            },
        ),
        migrations.CreateModel(
            name='ResidentialCondo',
            fields=[
                ('condo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='structure.condo')),
            ],
            options={
                'verbose_name': 'Residential Condo',
                'verbose_name_plural': 'Residential Condos',
                'db_table': 'residential_condo',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.license')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.platformadmin')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'db_table': 'platform',
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.platform'),
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('street', models.CharField(max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.residenceadmin')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.residentialcondo')),
            ],
            options={
                'verbose_name': 'Residence',
                'verbose_name_plural': 'Residences',
                'db_table': 'residence',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_people', models.IntegerField(verbose_name='allowed people')),
                ('is_open', models.BooleanField(default=True, verbose_name='open')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.residentialcondo')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
            },
        ),
    ]
