# Generated by Django 4.0.7 on 2022-09-01 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('qr', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Checkpoint',
                'verbose_name_plural': 'Checkpoints',
                'db_table': 'checkpoint',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_ini', models.TimeField(default=django.utils.timezone.now)),
                ('time_end', models.TimeField()),
                ('amount_people', models.IntegerField(default=10)),
                ('token', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Event Area',
                'verbose_name_plural': 'Event Areas',
                'db_table': 'event_area',
            },
        ),
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Event Reservation',
                'verbose_name_plural': 'Event Reservations',
                'db_table': 'event_reservation',
            },
        ),
        migrations.CreateModel(
            name='InvitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('identification', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Invitation Request',
                'verbose_name_plural': 'Invitation Requests',
                'db_table': 'invitation_request',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('end', models.DateField()),
                ('quantity', models.IntegerField(default=5)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('invited_first_name', models.CharField(max_length=255)),
                ('invited_last_name', models.CharField(max_length=255)),
                ('invited_identification', models.CharField(blank=True, max_length=15)),
                ('car_registration', models.CharField(max_length=255)),
                ('car_color', models.CharField(max_length=255)),
                ('car_brand', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_ini', models.TimeField(default=django.utils.timezone.now)),
                ('date_end', models.TimeField()),
                ('qr', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='ReservationRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Reservation Registry',
                'verbose_name_plural': 'Reservation Registries',
                'db_table': 'reservation_registry',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_ini', models.TimeField()),
                ('time_end', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
                'db_table': 'round',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='RouteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Route Area',
                'verbose_name_plural': 'Route Areas',
                'db_table': 'route_area',
            },
        ),
        migrations.CreateModel(
            name='RouteRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Route Round',
                'verbose_name_plural': 'Route Rounds',
                'db_table': 'route_round',
            },
        ),
        migrations.CreateModel(
            name='RouteSuperArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Route Super Area',
                'verbose_name_plural': 'Route Super Areas',
                'db_table': 'route_super_area',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Denied'), (3, 'Canceled'), (4, 'Expired'), (5, 'Finished')], default=0, null=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Delivery'), (1, 'Normal Visit'), (2, 'Worker'), (3, 'Taxi Visit'), (4, 'Walker Visit'), (5, 'Taxi Service'), (6, 'Not Invite Dedlivery'), (7, 'Not Invite Normal'), (8, 'Not Invite Taxi'), (9, 'Not Invite Walker'), (10, 'Provider Visit'), (11, 'Provider Visit Walker')])),
                ('is_qr', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'type',
            },
        ),
    ]
