# Generated by Django 4.0.7 on 2022-09-01 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
        ('structure', '0001_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesuperarea',
            name='condo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.condo'),
        ),
        migrations.AddField(
            model_name='routeround',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.round'),
        ),
        migrations.AddField(
            model_name='routeround',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.route'),
        ),
        migrations.AddField(
            model_name='routeround',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.security'),
        ),
        migrations.AddField(
            model_name='routearea',
            name='condo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.condo'),
        ),
        migrations.AddField(
            model_name='routearea',
            name='route_super_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.routesuperarea'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.routearea'),
        ),
        migrations.AddField(
            model_name='reservationregistry',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.reservation'),
        ),
        migrations.AddField(
            model_name='reservationregistry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.security'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.state'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.type'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.resident'),
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.event'),
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.type'),
        ),
        migrations.AddField(
            model_name='eventreservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.event'),
        ),
        migrations.AddField(
            model_name='eventreservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.reservation'),
        ),
        migrations.AddField(
            model_name='eventarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.area'),
        ),
        migrations.AddField(
            model_name='eventarea',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.event'),
        ),
        migrations.AddField(
            model_name='eventarea',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.state'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.resident'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.route'),
        ),
    ]
