# Generated by Django 4.0.7 on 2022-09-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('control', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.round')),
            ],
        ),
        migrations.CreateModel(
            name='SentryBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.checkpoint')),
            ],
            options={
                'verbose_name': 'Sentry Box',
                'db_table': 'sentry_box',
            },
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateField(max_length=6)),
                ('dutyshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.dutyshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='SentryBoxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(max_length=6)),
                ('sentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.sentrybox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.supervisor')),
            ],
            options={
                'verbose_name': 'Sentry Box Log',
                'db_table': 'sentry_box_log',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateField(max_length=6)),
                ('dutyshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.dutyshift')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'report',
            },
        ),
        migrations.AddField(
            model_name='dutyshift',
            name='sentry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.sentrybox'),
        ),
        migrations.AddField(
            model_name='dutyshift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.security'),
        ),
        migrations.CreateModel(
            name='CheckpointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.checkpoint')),
                ('dutyshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.dutyshift')),
            ],
            options={
                'verbose_name': 'Checkpoint Log',
                'db_table': 'checkpoint_log',
            },
        ),
    ]
