# Generated by Django 4.0.7 on 2022-09-01 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Not Seen'), (2, 'Attended')], default=0, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.resident')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alert',
            },
        ),
        migrations.CreateModel(
            name='ReceivedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('attended_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.security')),
            ],
            options={
                'verbose_name': 'Received Alert',
                'verbose_name_plural': 'Received Alerts',
                'db_table': 'received_alert',
            },
        ),
    ]
